from csv import writer
from datetime import timedelta
from time import time, perf_counter
from faker import Faker
from pandas import DataFrame
from colorama import init, Style, Fore

bright = Style.BRIGHT
green, blue, red, cyan, reset = Fore.GREEN + bright, Fore.BLUE + bright, Fore.RED + bright, Fore.CYAN, Fore.RESET
init(convert=True, autoreset=True)
fake = Faker()


def profile():
    profile_data = fake.profile()
    name = profile_data['name']
    first_name = name.split(" ")[0]
    last_name = name.split(" ")[1]
    email = profile_data['mail']
    username = profile_data['username']
    gender = ''.join(["Male" if profile_data['sex'] == 'M' else "Female"])
    ip_address = fake.ipv4()
    mobile_number = fake.numerify('(###)-###-####')
    country = fake.country()
    data_dict = {'name': [name], 'first_name': [first_name], 'last_name': [last_name], 'email': [email],
                 'username': [username], 'gender': [gender], 'ip_address': [ip_address], 'mobile_number': [mobile_number],
                 'country': [country]}
    data = DataFrame(data_dict)
    data.to_csv(file_name, mode='a', header=False, index=False)


def make_file():
    global file_name
    file_name = f'output_{perf_counter()}.csv'
    headerList = ['name', 'first_name', 'last_name', 'email', 'username', 'gender', 'ip_address', 'mobile_number', 'country']
    with open(file_name, 'a', newline='') as f:
        writer(f).writerow(headerList)


def credit():
    credit_text = f"""
               {red}UNLIMITED REAL DATA GENERATOR
{green}               
     ██▀███   ▄▄▄       ██░ ██  █    ██  ██▓    
    ▓██ ▒ ██▒▒████▄    ▓██░ ██▒ ██  ▓██▒▓██▒    
    ▓██ ░▄█ ▒▒██  ▀█▄  ▒██▀▀██░▓██  ▒██░▒██░    
    ▒██▀▀█▄  ░██▄▄▄▄██ ░▓█ ░██ ▓▓█  ░██░▒██░    
    ░██▓ ▒██▒ ▓█   ▓██▒░▓█▒░██▓▒▒█████▓ ░██████▒
    ░ ▒▓ ░▒▓░ ▒▒   ▓▒█░ ▒ ░░▒░▒░▒▓▒ ▒ ▒ ░ ▒░▓  ░
      ░▒ ░ ▒░  ▒   ▒▒ ░ ▒ ░▒░ ░░░▒░ ░ ░ ░ ░ ▒  ░
      ░░   ░   ░   ▒    ░  ░░ ░ ░░░ ░ ░   ░ ░   
       ░           ░  ░ ░  ░  ░   ░         ░  ░ {blue}code generated by Rahul.p\n
    """
    print(credit_text)


def main():
    credit()
    number = int(input("[+] Enter the number of profiles to create :- "))
    make_file()
    start_time = time()
    for _ in range(number + 1):
        print(f"{blue}[*] Creating profiles - ", _, end='\r')
        profile()
    time_output = time() - start_time
    sec = str(timedelta(seconds=(int(time_output)))).split(":")
    print(f"{blue}[*]{green} Time taken to generate data is -{reset} {sec[0]} H : {sec[1]} M : {sec[2]} S")
    print(f"{green}[~] Successfully completed [~]")


try:
    main()
except Exception as e:
    print(f"{red}\n[-] error message is {e}")
